"""add category fk, roles and permissions, audit log fields

Revision ID: 0002_category_fk_roles_audit
Revises: 0001_baseline
Create Date: 2026-08-27 17:36:52.086603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002_category_fk_roles_audit'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('entity_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('entity_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transactions_category_id_categories', 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_role_id_roles', 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###

    _seed_roles_and_permissions()
    _backfill_activity_log_actor()
    _backfill_transaction_category_fk()


def _seed_roles_and_permissions():
    conn = op.get_bind()

    permission_rows = [
        ("users.view", "View user accounts"),
        ("users.edit", "Edit user accounts"),
        ("transactions.manage", "View and manage any user's transactions"),
        ("categories.manage", "Manage system/shared categories"),
        ("analytics.view", "View platform analytics"),
        ("settings.manage", "Manage application settings"),
        ("admins.manage", "Manage admin users and their roles"),
    ]
    for key, description in permission_rows:
        conn.execute(
            sa.text("INSERT INTO permissions (key, description) VALUES (:key, :description)"),
            {"key": key, "description": description},
        )
    permission_ids = dict(conn.execute(sa.text("SELECT key, id FROM permissions")).all())

    role_ids = {}
    for name, description in [
        ("super_admin", "Full administrative access, including managing other admins"),
        ("admin", "General administrative access"),
        ("support", "Read-only access for support staff"),
    ]:
        role_ids[name] = conn.execute(
            sa.text("INSERT INTO roles (name, description) VALUES (:name, :description) RETURNING id"),
            {"name": name, "description": description},
        ).scalar()

    def grant(role_name, keys):
        for key in keys:
            conn.execute(
                sa.text("INSERT INTO role_permissions (role_id, permission_id) VALUES (:role_id, :permission_id)"),
                {"role_id": role_ids[role_name], "permission_id": permission_ids[key]},
            )

    grant("super_admin", permission_ids.keys())
    grant("admin", [k for k in permission_ids if k != "admins.manage"])
    grant("support", ["users.view", "analytics.view"])

    # Every already-promoted admin (the is_admin boolean still gates today's
    # admin routes) starts out as a super_admin under the new roles schema,
    # so nobody loses access when a later phase starts checking roles too.
    conn.execute(sa.text("UPDATE users SET role_id = :role_id WHERE is_admin"), {"role_id": role_ids["super_admin"]})


def _backfill_activity_log_actor():
    op.get_bind().execute(sa.text("UPDATE activity_logs SET actor_id = user_id WHERE actor_id IS NULL"))


def _backfill_transaction_category_fk():
    conn = op.get_bind()
    distinct_categories = conn.execute(sa.text("SELECT DISTINCT user_id, category, type FROM transactions")).all()

    for user_id, category_name, type_ in distinct_categories:
        existing = conn.execute(
            sa.text("SELECT id FROM categories WHERE user_id = :user_id AND name = :name AND type = :type"),
            {"user_id": user_id, "name": category_name, "type": type_},
        ).first()
        if existing:
            category_id = existing[0]
        else:
            category_id = conn.execute(
                sa.text(
                    "INSERT INTO categories (user_id, name, type) VALUES (:user_id, :name, :type) RETURNING id"
                ),
                {"user_id": user_id, "name": category_name, "type": type_},
            ).scalar()

        conn.execute(
            sa.text(
                "UPDATE transactions SET category_id = :category_id "
                "WHERE user_id = :user_id AND category = :name AND type = :type"
            ),
            {"category_id": category_id, "user_id": user_id, "name": category_name, "type": type_},
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_role_id_roles', type_='foreignkey')
        batch_op.drop_column('role_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_category_id_categories', type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')
        batch_op.drop_column('target_user_id')
        batch_op.drop_column('actor_id')

    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
